---
extends: default

ignore:
  - .dart_tool
  - .git
  - build
  - node_modules

rules:
  comments:
    level: error
    min-spaces-from-content: 1
  comments-indentation:
    level: error
  document-start:
    level: error
  line-length: disable
  truthy: disable
