name: flutter_news_sample
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  breakpoint: ^1.2.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.2+1
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^9.2.0
  freezed_annotation: ^1.1.0
  go_router: ^3.0.4
  hooks_riverpod: ^1.0.3
  shared_preferences: ^2.0.13
  state_notifier: ^0.7.2+1

dev_dependencies:
  build_runner: ^2.1.7
  flutter_gen_runner: ^4.1.6
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true

  generate: true

import_sorter:
  ignored_files:
    - \/lib\/generated_plugin_registrant\.dart
    - .*.freezed\.dart
    - .*\.g\.dart
    - .*\.gen\.dart
    - .*\.gr\.dart
    - .*\.mocks\.dart

flutter_gen:
  output: lib/config
