---
name: flutter_news_sample
description: "A new Flutter project."
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ^3.7.2

workspace:
  - packages/app
  - packages/widgetbook

flutter:
  generate: true
