name: flutter_news_sample
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.1 <4.0.0'

dependencies:
  breakpoint: ^1.2.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  dio: ^5.6.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_inappwebview: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_timezone: ^3.0.0
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.7
  hooks_riverpod: ^2.5.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.4.0
  package_info_plus: ^8.0.1
  path: ^1.9.0
  path_provider: ^2.1.4
  reactive_forms: ^17.0.1
  retrofit: ^4.2.0
  riverpod_annotation: ^2.3.5
  share_plus: ^10.0.2
  shared_preferences: ^2.3.2
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  timezone: ^0.9.4
  url_launcher: ^6.3.0

dev_dependencies:
  build_runner: ^2.4.12
  custom_lint: ^0.6.4
  flutter_gen_runner: ^5.7.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  go_router_builder: ^2.7.1
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  mocktail_image_network: ^1.2.0
  plugin_platform_interface: ^2.1.8
  retrofit_generator: ^8.2.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  share_plus_platform_interface: ^5.0.0
  slang_build_runner: ^3.31.0
  url_launcher_platform_interface: ^2.3.2

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

flutter_gen:
  output: lib/config
