# frozen_string_literal: true

source "https://rubygems.org"

gem "abbrev"
gem "fastlane"
gem "mutex_m"

plugins_path = File.join(File.dirname(__FILE__), "fastlane", "Pluginfile")
eval_gemfile(plugins_path) if File.exist?(plugins_path)
