---
include: package:very_good_analysis/analysis_options.yaml
analyzer:
  exclude:
    - /**/*.g.dart
linter:
  rules:
    depend_on_referenced_packages: false
    public_member_api_docs: false
    # dart format と require_trailing_commas が競合するため無効化
    require_trailing_commas: false
