# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Deploy Stg to App Distribution"
  lane :deploy_stg do
    firebase_app_distribution(
      app: ENV["DEPLOY_ANDROID_STG_APP"],
      firebase_cli_token: ENV["DEPLOY_ANDROID_STG_FIREBASE_CLI_TOKEN"],
      android_artifact_type: "APK",
      android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
      groups: ENV["DEPLOY_ANDROID_STG_TESTER_GROUPS"],
      release_notes: ENV["DEPLOY_ANDROID_STG_RELEASE_NOTES"],
    )
  end

  desc 'Deploy Prod to Google Play(Internal)'
  lane :deploy_prod do
    upload_to_play_store(
      package_name: ENV["DEPLOY_ANDROID_PROD_PACKAGE_NAME"],
      track: 'internal',
      release_status: 'draft',
      json_key: 'google-play-store-credentials.json',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
      skip_upload_apk: true,
    )
  end
end
