---
name: Deploy iOS (Stg)

env:
  DART_DEFINE_FILE_PATH: dart_define/stg.json

on:
  workflow_dispatch:
    inputs:
      pull_request_number:
        description: 'Pull Request Number'
        required: false
        type: string
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Get Flutter version from .fvmrc
        id: get_flutter_version
        run: |
          flutter_version="$(< .fvmrc jq -r .flutter)"
          echo "version=$flutter_version" >> "$GITHUB_OUTPUT"

      - name: Setup flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: "stable"
          flutter-version: ${{ steps.get_flutter_version.outputs.version }}
          cache: true

      - name: Run flutter pub get
        run: |
          flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@cf7216d52fba1017929b4d7162fabe2b30af5b49 # v1.262.0

      - name: Cache Ruby bundle
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ios/vendor/bundle
          key: ios-ruby-bundle-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/ios/Gemfile.lock') }}

      - name: Run bundle install
        working-directory: packages/app/ios
        run: |
          bundle config path vendor/bundle
          bundle install --clean

      - name: Create dart define file
        env:
          DART_DEFINE_FILE_JSON: ${{ secrets.DART_DEFINE_FILE_STG_JSON }}
        run: |
          echo "$DART_DEFINE_FILE_JSON" | base64 --decode > "$DART_DEFINE_FILE_PATH"

      - name: Create GoogleService-Info.plist
        env:
          FIREBASE_STG_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.FIREBASE_STG_GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          mkdir -p ios/Runner/Firebase/stg
          echo "$FIREBASE_STG_GOOGLE_SERVICE_INFO_PLIST" | base64 --decode > ios/Runner/Firebase/stg/GoogleService-Info.plist

      - name: Create AuthKey.p8
        env:
          APPLE_STORE_CONNECT_AUTH_KEY_P8: ${{ secrets.APPLE_STORE_CONNECT_AUTH_KEY_P8 }}
          APPLE_STORE_CONNECT_KEY_ID: ${{ vars.APPLE_STORE_CONNECT_KEY_ID }}
        run: |
          echo "$APPLE_STORE_CONNECT_AUTH_KEY_P8" | base64 --decode > "ios/AuthKey_${APPLE_STORE_CONNECT_KEY_ID}.p8"

      - name: Run fastlane ios deploy_stg
        working-directory: packages/app/ios
        env:
          APPLE_DEVELOPER_TEAM_ID: ${{ vars.APPLE_DEVELOPER_TEAM_ID }}
          APPLE_STORE_CONNECT_KEY_ID: ${{ vars.APPLE_STORE_CONNECT_KEY_ID }}
          APPLE_STORE_CONNECT_ISSUER_ID: ${{ vars.APPLE_STORE_CONNECT_ISSUER_ID }}
          IOS_STG_APP_IDENTIFIER: ${{ vars.IOS_STG_APP_IDENTIFIER }}
        run: |
          bundle exec fastlane ios build_stg

      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: stg-runner-ipa
          path: ios/Runner.ipa

  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Download artifact
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5.0.0
        with:
          name: stg-runner-ipa
          path: ios

      - name: Setup Ruby
        uses: ruby/setup-ruby@cf7216d52fba1017929b4d7162fabe2b30af5b49 # v1.262.0

      - name: Cache Ruby bundle
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          path: ios/vendor/bundle
          key: ios-ruby-bundle-${{ runner.os }}-${{ hashFiles('.ruby-version') }}-${{ hashFiles('**/ios/Gemfile.lock') }}

      - name: Run bundle install
        working-directory: packages/app/ios
        run: |
          bundle config path vendor/bundle
          bundle install --clean

      - name: Run fastlane ios deploy_stg
        env:
          DEPLOY_IOS_STG_APP: ${{ vars.DEPLOY_IOS_STG_APP }}
          DEPLOY_IOS_STG_FIREBASE_CLI_TOKEN: ${{ secrets.DEPLOY_IOS_STG_FIREBASE_CLI_TOKEN }}
          DEPLOY_IOS_STG_RELEASE_NOTES:
          DEPLOY_IOS_STG_TESTER_GROUPS: ${{ vars.DEPLOY_IOS_STG_TESTER_GROUPS }}
        working-directory: packages/app/ios
        run: |
          bundle exec fastlane ios deploy_stg

      - name: Post deploied comment
        uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
        if: ${{ github.event.inputs.pull_request_number != '' }}
        env:
          MESSAGE: |
            Deploied iOS (Stg) to Firebase App Distribution
        with:
          script: |
            if (Number.isInteger(Number.parseInt("${{ inputs.pull_request_number }}"))) {
              github.rest.issues.createComment({
                issue_number: Number.parseInt("${{ inputs.pull_request_number }}"),
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: process.env.MESSAGE
              })
            }
