---
name: Flutter lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version-file: pubspec.yaml
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get

      - name: Check diff for pubspec.yaml and pubspec.lock
        run: |
          git add .
          git diff --cached --exit-code

      - name: dart run build_runner build
        run: |
          dart run build_runner build -d

      - name: Check diff for generated files
        run: |
          git add .
          git diff --cached --exit-code

      - name: dart format
        run: |
          find ./lib ./test -name "*.dart" -not \( -name "*.freezed.dart" -o -name "*.g.dart" -o -name "*.gen.dart" -o -name "*.gr.dart" -o -name "*.graphql.dart" -o -name "*.mock.dart" \) -exec dart format -o none --set-exit-if-changed {} +

      - name: flutter analyze
        run: |
          flutter analyze --no-fatal-infos
