---
name: Flutter Integration Test on App iOS

on:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTION: microsoft
  JAVA_VERSION: 17
  DART_DEFINE_FILE_PATH: dart_define/integration_test_ios.json
  WIREMOCK_VERSION: 3.9.2

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd # v1.6.0
        with:
          xcode-version: latest-stable

      - name: Setup Ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0

      - name: Install CocoaPods
        run: |
          gem install cocoapods

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download WireMock
        run: |
          curl -L "https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/${WIREMOCK_VERSION}/wiremock-standalone-${WIREMOCK_VERSION}.jar" -o wiremock-standalone.jar

      - name: Run WireMock
        run: |
          java -jar wiremock-standalone.jar --port 8080 &

      - name: Get Flutter version from .fvmrc
        id: get_flutter_version
        run: |
          flutter_version="$(< .fvmrc jq -r .flutter)"
          echo "version=$flutter_version" >> "$GITHUB_OUTPUT"

      - name: Setup flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: "stable"
          flutter-version: ${{ steps.get_flutter_version.outputs.version }}
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get

      - name: Create dart define file
        working-directory: packages/app
        env:
          DART_DEFINE_FILE_JSON: ${{ secrets.DART_DEFINE_FILE_INTEGRATION_TEST_IOS_JSON }}
        run: |
          echo "$DART_DEFINE_FILE_JSON" | base64 --decode > "$DART_DEFINE_FILE_PATH"
          ls -l "$DART_DEFINE_FILE_PATH"

      - name: Create GoogleService-Info.plist
        working-directory: packages/app
        env:
          FIREBASE_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.FIREBASE_STG_GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          mkdir -p ios/Runner/Firebase/stg/
          echo "$FIREBASE_GOOGLE_SERVICE_INFO_PLIST" | base64 --decode > ios/Runner/Firebase/stg/GoogleService-Info.plist
          ls -l ios/Runner/Firebase/stg/

      - name: Launch iOS simulator
        run: |
          xcrun simctl list devices
          xcrun simctl list runtimes
          xcrun simctl create "iPhone for Test" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-17-4"
          device=$(xcrun simctl list devices | grep "iPhone for Test" | grep -oE "[0-9A-F-]{36}")
          xcrun simctl boot "$device"

      - name: Run flutter drive
        working-directory: packages/app
        # テストは成功「All tests passed.」するが、その後の `Simulator device failed to terminate $(PRODUCT_BUNDLE_IDENTIFIER).` でエラー終了する
        # そのため、`set +e` でエラーを無視し、「All tests passed.」の結果で成功とする
        # issue: https://github.com/flutter/flutter/issues/129338
        run: |
          set +e
          flutter drive \
            --dart-define-from-file ${{ env.DART_DEFINE_FILE_PATH }} \
            --driver test_driver/integration_test.dart \
            --target integration_test/suite/general_test.dart | tee test.log
          set -e

          grep -q "All tests passed." test.log
