---
name: Flutter Integration Test on App Android

on:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  ANDROID_EMULATOR_API_LEVEL: 29
  JAVA_DISTRIBUTION: microsoft
  JAVA_VERSION: 17
  DART_DEFINE_FILE_PATH: dart_define/integration_test_android.json
  WIREMOCK_VERSION: 3.9.2

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Setup Java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download WireMock
        run: |
          curl -L "https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/${WIREMOCK_VERSION}/wiremock-standalone-${WIREMOCK_VERSION}.jar" -o wiremock-standalone.jar

      - name: Run WireMock
        run: |
          java -jar wiremock-standalone.jar --port 8080 &

      - name: Get Flutter version from .fvmrc
        id: get_flutter_version
        run: |
          flutter_version="$(< .fvmrc jq -r .flutter)"
          echo "version=$flutter_version" >> "$GITHUB_OUTPUT"

      - name: Setup flutter
        uses: subosito/flutter-action@fd55f4c5af5b953cc57a2be44cb082c8f6635e8e # v2.21.0
        with:
          channel: "stable"
          flutter-version: ${{ steps.get_flutter_version.outputs.version }}
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get

      - name: Create dart define file
        working-directory: packages/app
        env:
          DART_DEFINE_FILE_JSON: ${{ secrets.DART_DEFINE_FILE_INTEGRATION_TEST_ANDROID_JSON }}
        run: |
          echo "$DART_DEFINE_FILE_JSON" | base64 --decode > "$DART_DEFINE_FILE_PATH"
          ls -l "$DART_DEFINE_FILE_PATH"

      - name: Create google-services.json
        working-directory: packages/app
        env:
          FIREBASE_GOOGLE_SERVICE_JSON: ${{ secrets.FIREBASE_STG_GOOGLE_SERVICE_JSON }}
        run: |
          mkdir -p android/app/src/stg
          echo "$FIREBASE_GOOGLE_SERVICE_JSON" | base64 --decode > android/app/src/stg/google-services.json
          ls -l android/app/src/stg/google-services.json

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run flutter drive
        uses: reactivecircus/android-emulator-runner@1dcd0090116d15e7c562f8db72807de5e036a4ed # v2.34.0
        with:
          api-level: ${{ env.ANDROID_EMULATOR_API_LEVEL }}
          working-directory: packages/app
          script: >-
            flutter drive
            --dart-define-from-file ${{ env.DART_DEFINE_FILE_PATH }}
            --driver test_driver/integration_test.dart
            --target integration_test/suite/general_test.dart
