---
name: Flutter Integration Test on iOS

on:
  pull_request:
  push:
    branches:
      - main
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

env:
  JAVA_DISTRIBUTION: microsoft
  JAVA_VERSION: 17
  DART_DEFINE_FILE_PATH: dart_define/integration_test_ios.json
  WIREMOCK_VERSION: 3.9.2

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 30
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Ruby
        uses: ruby/setup-ruby@a2bbe5b1b236842c1cb7dd11e8e3b51e0a616acc # v1.202.0

      - name: Install CocoaPods
        run: |
          gem install cocoapods

      - name: Setup Java
        uses: actions/setup-java@8df1039502a15bceb9433410b1a100fbe190c53b # v4.5.0
        with:
          distribution: ${{ env.JAVA_DISTRIBUTION }}
          java-version: ${{ env.JAVA_VERSION }}

      - name: Download WireMock
        run: |
          curl -L "https://repo1.maven.org/maven2/org/wiremock/wiremock-standalone/${WIREMOCK_VERSION}/wiremock-standalone-${WIREMOCK_VERSION}.jar" -o wiremock-standalone.jar

      - name: Run WireMock
        run: |
          java -jar wiremock-standalone.jar --port 8080 &

      - name: Get Flutter version from .fvmrc
        id: get_flutter_version
        run: |
          flutter_version="$(< .fvmrc jq -r .flutter)"
          echo "version=$flutter_version" >> "$GITHUB_OUTPUT"

      - name: Setup flutter
        uses: subosito/flutter-action@74af56c5ed2697ba4621264652728e8d217e53d3 # v2.17.0
        with:
          channel: "stable"
          flutter-version: ${{ steps.get_flutter_version.outputs.version }}
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get

      - name: Create dart define file
        env:
          DART_DEFINE_FILE_JSON: ${{ secrets.DART_DEFINE_FILE_INTEGRATION_TEST_IOS_JSON }}
        run: |
          echo "$DART_DEFINE_FILE_JSON" | base64 --decode > "$DART_DEFINE_FILE_PATH"
          ls -l "$DART_DEFINE_FILE_PATH"

      - name: Create GoogleService-Info.plist
        env:
          FIREBASE_GOOGLE_SERVICE_INFO_PLIST: ${{ secrets.FIREBASE_STG_GOOGLE_SERVICE_INFO_PLIST }}
        run: |
          mkdir -p ios/Runner/Firebase/stg/
          echo "$FIREBASE_GOOGLE_SERVICE_INFO_PLIST" | base64 --decode > ios/Runner/Firebase/stg/GoogleService-Info.plist
          ls -l ios/Runner/Firebase/stg/

      - name: Launch iOS simulator
        run: |
          xcrun simctl list devices
          xcrun simctl list runtimes
          xcrun simctl create "iPhone for Test" "com.apple.CoreSimulator.SimDeviceType.iPhone-15" "com.apple.CoreSimulator.SimRuntime.iOS-17-4"
          device=$(xcrun simctl list devices | grep "iPhone for Test" | grep -oE "[0-9A-F-]{36}")
          xcrun simctl boot "$device"

      - name: Run flutter drive
        # テストは成功「All tests passed.」するが、その後の `Simulator device failed to terminate $(PRODUCT_BUNDLE_IDENTIFIER).` でエラー終了する
        # そのため、`set +e` でエラーを無視し、「All tests passed.」の結果で成功とする
        # issue: https://github.com/flutter/flutter/issues/129338
        run: |
          set +e
          flutter drive \
            --no-pub \
            --dart-define-from-file ${{ env.DART_DEFINE_FILE_PATH }} \
            --driver test_driver/integration_test.dart \
            --target integration_test/suite/general_test.dart | tee test.log
          set -e

          grep -q "All tests passed." test.log
