# actionlint　と ghalint を使って GitHub Actions の構文をチェックする
#
# - actionlint: https://github.com/rhysd/actionlint
# - ghalint: https://github.com/suzuki-shunsuke/ghalint
---
name: GitHub Actions Lint

on:
  pull_request:
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml
  push:
    branches:
      - main
    paths:
      - .github/workflows/*.yaml
      - .github/workflows/*.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Download actionlint
        # NOTE: アップデートする場合は、ACTIONLINT_VERSION, ACTIONLINT_CHECKSUM を更新してください
        env:
          ACTIONLINT_VERSION: 1.7.1
          ACTIONLINT_OS: linux
          ACTIONLINT_ARCH: amd64
          ACTIONLINT_CHECKSUM: f53c34493657dfea83b657e4b62cc68c25fbc383dff64c8d581613b037aacaa3
        run: |
          curl -L -o actionlint.tar.gz "https://github.com/rhysd/actionlint/releases/download/v${ACTIONLINT_VERSION}/actionlint_${ACTIONLINT_VERSION}_${ACTIONLINT_OS}_${ACTIONLINT_ARCH}.tar.gz"
          if [ "$(shasum -a 256 actionlint.tar.gz)" != "${ACTIONLINT_CHECKSUM}  actionlint.tar.gz" ]; then
            echo "checksum mismatch"
            echo "expected: ${ACTIONLINT_CHECKSUM}  actionlint.tar.gz"
            echo "actual: $(shasum -a 256 actionlint.tar.gz)"
            exit 1
          fi
          tar xzf actionlint.tar.gz
          ./actionlint -version

      - name: Run actionlint
        run: ./actionlint -color

      - name: Download ghalint
        # NOTE: アップデートする場合は、GHALINT_VERSION, GHALINT_CHECKSUM を更新してください
        env:
          GHALINT_VERSION: 0.2.12
          GHALINT_OS: linux
          GHALINT_ARCH: amd64
          GHALINT_CHECKSUM: 722d3420fff4f9a0d7b38b3654dfcddb4f1f6e2adbb3bba013f2d9eed406d9d5
        run: |
          curl -L -o ghalint.tar.gz "https://github.com/suzuki-shunsuke/ghalint/releases/download/v${GHALINT_VERSION}/ghalint_${GHALINT_VERSION}_${GHALINT_OS}_${GHALINT_ARCH}.tar.gz"
          if [ "$(shasum -a 256 ghalint.tar.gz)" != "${GHALINT_CHECKSUM}  ghalint.tar.gz" ]; then
            echo "checksum mismatch"
            echo "expected: ${GHALINT_CHECKSUM}  ghalint.tar.gz"
            echo "actual: $(shasum -a 256 ghalint.tar.gz)"
            exit 1
          fi
          tar xzf ghalint.tar.gz
          ./ghalint version

      - name: Run ghalint
        run: ./ghalint run
