---
name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"
  push:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
