---
name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"
  push:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
