---
name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install yamllint
        run: sudo apt-get install yamllint

      - name: Lint YAML files
        run: yamllint .
