---
name: yamllint

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"
  push:
    branches:
      - main
    paths:
      - "**/*.yaml"
      - "**/*.yml"
      - ".yamllint.yaml"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Lint YAML files
        run: yamllint .
